
services:
    morphos:
        image: ghcr.io/danvergara/morphos-server:latest
        container_name: morphos
        restart: unless-stopped

        networks:
            - traefik

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.morphos.rule: Host(`morphos.domain.com`)
            traefik.http.routers.morphos.entrypoints: https
            traefik.http.services.morphos.loadbalancer.server.port: 8080

networks:
    traefik:
        external: true
