
services:
    socket-proxy:
        image: lscr.io/linuxserver/socket-proxy:latest
        container_name: socket-proxy
        restart: unless-stopped

        read_only: true

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        
        networks:
            - socket-proxy

        tmpfs:
            - /run

        env_file:
            - .env

        ports:
            - 2375:2375


networks:
    socket-proxy:
        name: socket-proxy
