
services:
    code-server:
        image: codercom/code-server:latest
        container_name: code-server

        user: '1000:1000'

        volumes:
            - '~/code-server:/home/coder/project'
            - './data/config:/home/coder/.config'
            - './data/local:/home/coder/.local'

        environment:
            - DOCKER_USER=$USER
            - CODER_DISABLE_PASSWORD_AUTH=true

        networks:
            - traefik

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.code.rule: Host(`code.domain.com`)
            traefik.http.routers.code.entrypoints: https
            traefik.http.routers.code.middlewares: authelia@docker
            traefik.http.services.code.loadbalancer.server.port: 8080

networks:
    traefik:
        external: true