

services:
    wallos:
        container_name: wallos
        image: bellamy/wallos:latest
        restart: unless-stopped

        environment:
            TZ: 'America/Vancouver'

        volumes:
            - './db:/var/www/html/db'
            - './logos:/var/www/html/images/uploads/logos'

        networks:
            - traefik
        
        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.wallos.rule: Host(`wallos.domain.com`)
            traefik.http.routers.wallos.entrypoints: https
            traefik.http.routers.wallos.middlewares: authelia@docker
            traefik.http.services.wallos.loadbalancer.server.port: 80

networks:
    traefik:
        external: true