# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

output: prefixed

tasks:
    all-down:
        dir: ~/docker
        cmds:
            - for:
                - code-server
                - dashboard
                - gossip
                - grafana
                - infrared
                - it-tools
                - media
                - onedev
                - portainer
                - pterodactyl
                - uptime-kuma
                - wallos

                # Depend on minio
                - wings
                - zipline

                # Storage
                - minio

                # We do these last since everything else depends on them.
                - authelia
                - traefik
                - wireguard-client

              task: toggle-stack
              vars:
                  CONTAINER: '{{.ITEM}}'
                  DIRECTION: down

    all-up:
        dir: ~/docker
        cmds:
            - for:
                # We do these first since everything else depends on them.
                - authelia
                - traefik
                - wireguard-client

                # Storage
                - minio

                - code-server
                - dashboard
                - gossip
                - grafana
                - infrared
                - it-tools
                - media
                - onedev
                - portainer
                - pterodactyl
                - uptime-kuma
                - wallos
                - wings
                - zipline

              task: toggle-stack
              vars:
                  CONTAINER: '{{.ITEM}}'
                  DIRECTION: up -d


    toggle-stack:
        internal: true
        prefix: '{{.CONTAINER}}'

        dir: '{{.CONTAINER}}'
        cmds: 
            - docker compose {{ .DIRECTION }}


    validate-auth:
        cmd: docker exec -it authelia authelia validate-config -c /config/configuration.yml

    generate-secret:
        cmd: docker exec -it authelia authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
