services:
    bytebase:
        container_name: bytebase
        image: bytebase/bytebase:latest

        restart: unless-stopped
        
        volumes:
            - ./data:/var/opt/bytebase

        expose:
          - 8080

        networks:
            - traefik
            - bytebase

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.bytebase.rule: Host(`bytebase.domain.com`)
            traefik.http.routers.bytebase.entrypoints: https
            traefik.http.routers.bytebase.middlewares: authelia@docker
            traefik.http.services.bytebase.loadbalancer.server.port: 8080

networks:
    bytebase:
        name: bytebase
    traefik:
        external: true

