version: '3'

services:
    portainer:
        image: corentinth/it-tools:latest
        container_name: it-tools
        restart: unless-stopped

        networks:
            - traefik

        labels:
            traefik.enable: true
            traefik.http.routers.it-tools.rule: Host(`it-tools.domain.com`)
            traefik.http.routers.it-tools.entrypoints: https
            traefik.http.services.it-tools.loadbalancer.server.port: 80

networks:
    traefik:
        external: true
