

services:
    server:
        image: 1dev/server
        container_name: onedev
        restart: unless-stopped

        volumes:
            - ./data/onedev:/opt/onedev
            - /var/run/docker.sock:/var/run/docker.sock:ro

        networks:
            - traefik

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.onedev.rule: Host(`onedev.domain.com`)
            traefik.http.routers.onedev.entrypoints: https
            traefik.http.services.onedev.loadbalancer.server.port: 6610

networks:
    traefik:
        external: true

