version: '3'

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        restart: always

        network_mode: host

        cap_add:
            - NET_ADMIN
            - SYS_MODULE

        volumes:
            - ./data:/config

        labels:
            diun.enable: true

networks:
    traefik:
        external: true
