# version: "3"
# services:
#     gluetun:
#         image: qmcgaw/gluetun
#         container_name: gluetun

#         cap_add:
#             - NET_ADMIN

#         devices:
#             - /dev/net/tun:/dev/net/tun

#         volumes:
#             - ./data:/gluetun

#         env_file:
#             - .env

#     radarr:

#     sonarr:
    
#     whisparr:

#     prowlarr:

#     qBitTorrent:
        


# networks:
#     traefik:
#         external: true
