version: "3.8"

services:
    
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: unless-stopped
        command: --api.insecure=true --providers.docker

        networks:
            - traefik
        
        env_file:
            - .env

        expose:
            - 8082

        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443

        volumes:
            - ./data/acme.json:/acme.json
            - ./data/access.log:/access.log
            - ./data/traefik.log:/traefik.log
            - ./data/traefik.yml:/traefik.yml
            - /var/run/docker.sock:/var/run/docker.sock:ro

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.dashboard.rule: Host(`traefik.domain.com`)
            traefik.http.routers.dashboard.entrypoints: https
            traefik.http.routers.dashboard.service: api@internal
            traefik.http.routers.dashboard.middlewares: authelia@docker
            traefik.http.services.dashboard.loadbalancer.server.port: 8080


networks:
    traefik:
        name: traefik
        ipam:
            driver: default
            config:
                - subnet: 10.1.0.0/16
