

services:
    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        restart: unless-stopped

        user: '1000:1000'

        env_file:
            - .env
        
        volumes:
            - ./data/grafana:/var/lib/grafana

        networks:
            - traefik
            - metrics

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.grafana.rule: Host(`grafana.domain.com`)
            traefik.http.routers.grafana.entrypoints: https
            traefik.http.services.grafana.loadbalancer.server.port: 3000

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        restart: unless-stopped

        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro

        networks:
            - metrics

        expose:
            - 8080

        labels:
            diun.enable: true

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: unless-stopped

        command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug

        networks:
            - metrics
            - traefik

        volumes:
            - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus:/prometheus

        expose:
            - 9090

        labels:
            diun.enable: true


    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        command:
            - '--path.rootfs=/host'
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'

        labels:
            diun.enable: true

    kasa-exporter:
        build: ../git-sources/kasa-exporter/
        container_name: kasa-exporter
        restart: unless-stopped

        networks:
            - metrics

        expose:
            - 9089

networks:
    traefik:
        external: true

    metrics:
        name: metrics

volumes:
    prometheus:
