debug: ENC[AES256_GCM,data:54pcA/g=,iv:Zf652wKa13thDmJkZtHr6qdiNSASBERQ9iqBdQsTqjc=,tag:0qmsXkAVFsgdKoAMHOhFyg==,type:bool]
app_name: ENC[AES256_GCM,data:m+YYFzRj8iOe7lU=,iv:8riPGtGIP9A0ctGyACl2XMLmpg1tzSv+mVvyM9YLehM=,tag:RRO1d26/gWyJRSiMTVeILw==,type:str]
uuid: ENC[AES256_GCM,data:D9ZPKzD3ZiaaoLYfYksysdu1s4m1vhuJhixn+6qFWmarP/P/,iv:Bp68jSQzLLYTY2qUNz5R0K7RDcG/Sjafkf1npAceBvA=,tag:9HpI0Su1mZHm5pX8d2H4wg==,type:str]
token_id: ENC[AES256_GCM,data:SYYlEcHFeOor1GclIu1aiQ==,iv:rJZVaa2wEWhtTAiHH9W4qWyVk1ZWku1RhYeMHxX22yk=,tag:Ba3FpPLKfjeXojjDVQyGCA==,type:str]
token: ENC[AES256_GCM,data:sd81zqxWP5utvV7W4rW3qkmaMjRHTdGHDpn+NK4FDCXmTteBm/ZXW9FzHDj6luzsaRLe/RPUfvXyeUtjaHklMQ==,iv:uAu4ikkWSIcHuXUhw4n53sQcLwnBjYjsJXQWXludDtQ=,tag:JJNTSpJ8VMhkdLmJzyiNmw==,type:str]
api:
    host: ENC[AES256_GCM,data:9VcWu2Qpew==,iv:U4aCB3Cw9z/QKRmLPQ5A8GumD53kPxC0wko0NqnYm1Y=,tag:Ldrv+daAHmvkT5lXhhT8Pw==,type:str]
    port: ENC[AES256_GCM,data:QAK8,iv:msHe5ayqLHZNuyTYXBlEIhtcuOkCI5BQM6c+jhJFlbs=,tag:BlAw/7TmTe3pxEZfFYn+RQ==,type:int]
    ssl:
        enabled: ENC[AES256_GCM,data:4kbcF64=,iv:Rt2wMmysPmDZgMnnaHgQLVJfhbtouu9WsvzYs2dZI08=,tag:F721RHGB3IIVfAAYXIyCZw==,type:bool]
        cert: ENC[AES256_GCM,data:j/jhnNQUG0485g3jJO8KuHzB/fA94rxNzln1EhiIOqvAZHzKQM20q0tVtdlfvArQImE=,iv:Jypo7MN7k0/kRYJdQTe32j1GhwGRjFEJCQi1ddJpQSs=,tag:pB6bNf1xZI6kG5w0tK582w==,type:str]
        key: ENC[AES256_GCM,data:HCqVWXd9OPxy239wmjdAfAUa1O5K6Z6vnAhYzzA08hnsOKyYLdh5nN/Bn+eiUjxJ,iv:V/uP6QPVxeH6uTh1IAyW5nU9+YBXTFrDFpJvGDJb7fw=,tag:lPg2+7fkT83zj5e0hBPE0w==,type:str]
    disable_remote_download: ENC[AES256_GCM,data:29106HE=,iv:UyLYlxKsmMNV3icO3mT4iBw5cZ9+aEHK8l8HISRxP/k=,tag:20k+Q8osCHdrw9ImZrfizg==,type:bool]
    upload_limit: ENC[AES256_GCM,data:tIBZ,iv:DGx9f3SDPL2YKM75oOOnskM7CE04tSc6c/uqt1R4dqk=,tag:JCf8wWkFvI6ft9JYysf3bg==,type:int]
    trusted_proxies: []
system:
    root_directory: ENC[AES256_GCM,data:ZqS/wSTocLB8WcRQNae3DcbXzx/PiQ==,iv:X2mS8lqKgwqm1emsSn2lr3p11MIoXsy5C9xJ4jyRpVw=,tag:u5Xu+AGfuSxxNkEIMqRTNQ==,type:str]
    log_directory: ENC[AES256_GCM,data:XyCYLHtvOCB8nWrg2ARLMeQ/dFI=,iv:74QMG1PldorctCIyPI6EUbcZxwTQRFfErmJZ/uXaK/w=,tag:sSPKH0DGFCPEZlmZC+3+JA==,type:str]
    data: ENC[AES256_GCM,data:jvIClgE6ESqIAao4Sa17RzvwzGSG7Mh1nwmzURBu,iv:fOaUdCDQNBp+G+BRWT0sBa9nOPtUHyv9QZCjRDn86c4=,tag:JBlAg2ibA+cZ5ZtwkMIZPw==,type:str]
    archive_directory: ENC[AES256_GCM,data:q1ALbGh+qqGh5DN5HLM4x4Z35HqV33c2WBgddpISKQ==,iv:ng9ahjL91NWdg37GDm1LE7e8sfEd6MONhXNB5svAw6I=,tag:v1BwQ4gJigJJJW2VyInwVA==,type:str]
    backup_directory: ENC[AES256_GCM,data:gjPZPXMheuQVqJVtIWfxWOGOoTuhp5cNZyTmFTnH,iv:CA4w9AlSnWjGMsZVE7LnJ5ykIdoBn48t8btix4j7JKE=,tag:SeMMmT3L0UlXTKbV3S1STQ==,type:str]
    tmp_directory: ENC[AES256_GCM,data:k6MyP26dGSVbtJGzisE/Rw==,iv:MDb3d8wTTHQ1nXMkbqqr2TQ8muEZNXs8rXdp4AwVQow=,tag:YJpwnA7CpWML8ug4G7zEvw==,type:str]
    username: ENC[AES256_GCM,data:E2h6kjnyGBOpQSA=,iv:m3/zZXyWkRTmkiUSk85nQTNDPNquMKsIARFAIbB3boE=,tag:/Uz/vZab7Wgm6v8JjVQa6Q==,type:str]
    timezone: ENC[AES256_GCM,data:bKho745ngsNAyjNGNAeEd+c=,iv:M9ac7tAofYAL3p5YWjWPD/f7R42v79B8veFcyBS7Ebs=,tag:lFCnGAwA9SCG5yNgwXJg+g==,type:str]
    user:
        rootless:
            enabled: ENC[AES256_GCM,data:HdTZbKM=,iv:9aft24Y/MtjVBwgHCUfMPZy5aYIHHQTpJ0ItthJTWco=,tag:1K35OOQIthIlfSt43QU+mg==,type:bool]
            container_uid: ENC[AES256_GCM,data:FA==,iv:bazZqf2n5uukxBzD2/VCt5QlH8smIPVHlwLXrUKKvcQ=,tag:d3aA3yK4dLp4ZYdAbyx+Xg==,type:int]
            container_gid: ENC[AES256_GCM,data:+g==,iv:Q6P0WoWRvunRJSZckLNw+0/3qGDFbXa97Nf35wCpCto=,tag:EboasgI56Qnqelar17JwfQ==,type:int]
        uid: ENC[AES256_GCM,data:q6oH,iv:3Wdqv/LO9voJ8fWOqD4n7MLsQ2VHHU8kWnnrp2Glhxc=,tag:Vlb3CqDMGddwhwSs29LwKg==,type:int]
        gid: ENC[AES256_GCM,data:RVEh,iv:QJ2voChsHPsiIRpjExAEgErkWSy22KHRzlrD7z98ZDk=,tag:o/F7sJXGGxbpkmNbb+sL8A==,type:int]
    passwd:
        enabled: ENC[AES256_GCM,data:c0loNy0=,iv:0zfZ8F1CyAfTVvMJXLgrCj3VWBOr5pEiSqGL2TaAFCI=,tag:Rs+y7Kv1yzus3Kgics1rGg==,type:bool]
        directory: ENC[AES256_GCM,data:rM/tYWh6pJcosBESUgk=,iv:zK2NJxxS5aMy2DG85jKYUIIhLk1zux1JnYpqmlKDY2Y=,tag:lap+CzRayocstwiM/uZYLg==,type:str]
    disk_check_interval: ENC[AES256_GCM,data:8T8+,iv:sGBRkFAMcmhiUj6Gs8rGbh52IZm7dljFyOtbzlVTluw=,tag:xrOkGZbfHjknJc1o7CRZmw==,type:int]
    activity_send_interval: ENC[AES256_GCM,data:42A=,iv:vUcHdZNHRYCnHLwzS39iAol2I9Qt1u73BKHpdwTDEqA=,tag:sEE/TRI2sSJqf9U/vYpRwA==,type:int]
    activity_send_count: ENC[AES256_GCM,data:XgdS,iv:/VxruSHJRdTxioPkdiINv2ejCRGcZFXrKcrB9bbYqWQ=,tag:GFPImpmRSRNyYz4JLALRGw==,type:int]
    check_permissions_on_boot: ENC[AES256_GCM,data:ifCDNQ==,iv:jieVAAmPmt+0lCDp+PSwIS713wPH1c/MsRaMBK4fvuU=,tag:mRr20cvtGMQxaOCgscf3wg==,type:bool]
    enable_log_rotate: ENC[AES256_GCM,data:CESASg==,iv:r64AQ/EZqU8qAYkQWGT3oFqzi71wo87YRfuRAH2UYMk=,tag:GcSXrQjeTyYXnNIY1n31dQ==,type:bool]
    websocket_log_count: ENC[AES256_GCM,data:iZET,iv:DrQpUCB/xJetGzatb4vyzwu8I9F642L5dIungnUZWbo=,tag:Yf3MuJlTerAlu7Mjk+9GRA==,type:int]
    sftp:
        bind_address: ENC[AES256_GCM,data:q4mbRgWltw==,iv:6TWg2PKVcCujyRuwu4Zm7n3i9ukDw2gb/9VNFGqLYEg=,tag:ysHyrjMZT2cWpLFfjHFRug==,type:str]
        bind_port: ENC[AES256_GCM,data:Dbc5jA==,iv:Pk/GgvGQOzSqtcM1ke5VF8IYCxO8fub2oegxjGABR1s=,tag:aA45MoYOnRwN3iAtXZu9OA==,type:int]
        read_only: ENC[AES256_GCM,data:kUytLWY=,iv:BPgFOoFlNUlocjHVWtd+k+wXeZMCzyyMlr/lL/5wZgA=,tag:860zJIGdXMdq0+tK6lUG1Q==,type:bool]
    crash_detection:
        enabled: ENC[AES256_GCM,data:GddsiQ==,iv:noTNGKmxjhSOlA0XRWfNRqpXiBfbRDNNqg6m/x1nAEg=,tag:GZYUjiBU+T0H7l9TJklpPQ==,type:bool]
        detect_clean_exit_as_crash: ENC[AES256_GCM,data:TZsBgQ==,iv:wwk3Vg6fRJMLu7+a4swTeQ83g35bQFdpwcNthedVxWw=,tag:7gbE2TlqbIHaUBWeskVTyQ==,type:bool]
        timeout: ENC[AES256_GCM,data:+RI=,iv:gbDW/uGVJ10uoGVmaeiL0OeVEhjVZxQYJir+yutkjIA=,tag:IAM3i1wsa2wZnnRZ8NidqA==,type:int]
    backups:
        write_limit: ENC[AES256_GCM,data:mw==,iv:f73qMj2dTvv/+FBL7u6bQhsPjOhhMQtpgTsLmNvG218=,tag:bnMruSnzf+ADPJqmIR2p/A==,type:int]
        compression_level: ENC[AES256_GCM,data:1EBf8dPcJ9SNCQ==,iv:afkYFTgP1qpP/g6+KRjtWebCjvxbBIuggXzsC3fxBMQ=,tag:++OxAzADkLu8cES+II9bvA==,type:str]
    transfers:
        download_limit: ENC[AES256_GCM,data:JQ==,iv:Dfz9u4x++OpGIHi+kzElqgg0XSLwZ4SZh+p9f3A4n/w=,tag:8tWVWYIzDbghiUlu5tvGdA==,type:int]
    openat_mode: ENC[AES256_GCM,data:KTgBnw==,iv:xVUedQ82bwGZ5gMwZW/4Pf3beZ0l1xZcexAZWObuWDU=,tag:sfULWP5TETHpFGledM1J9A==,type:str]
docker:
    network:
        interface: ENC[AES256_GCM,data:3RGJjYK7nhc=,iv:vIU59DuftMoo16N/pgn+J63bcGyiUFqIygwHp+hhBWk=,tag:isSU9qM2rUfTq9/DM+WMww==,type:str]
        dns:
            - ENC[AES256_GCM,data:TFXYyhMugg==,iv:RUDAxJs+X8CgP/nZuzB6suqkJ4qtNO7GvAQIrGCyZdc=,tag:5VrR39LblU0khz3lMv8nDA==,type:str]
            - ENC[AES256_GCM,data:HIFf2Rv1ZQ==,iv:7dT++hV5xxYVW6XX97olFHEg0aOBtU6U9Yq3qRS6q8I=,tag:AbLIzT28xDXMQEJAhxvrHw==,type:str]
        name: ENC[AES256_GCM,data:jA1wTJ21DzQDx8c=,iv:9YUGb7VIZOSnUCMp9pGjcsK2y+nALAOFbF2DmCclJaw=,tag:YXIyb2TwUol6tAy7OsU+oA==,type:str]
        ispn: ENC[AES256_GCM,data:WpDTWFw=,iv:YGMjATD3bND4FHJke9c9MH4M3ZVIri9yq3GkKMSi3XE=,tag:+WucCjoKm1l6J6kVmoT8xw==,type:bool]
        driver: ENC[AES256_GCM,data:JO54mLWc,iv:2qA8YQCZNMFoSt3RP7O08JcDqLZFrsD/NdfRKrOGQMk=,tag:fgHXOvtT7tki0an19xDKDw==,type:str]
        network_mode: ENC[AES256_GCM,data:/eBp18wUcCUSitw=,iv:xqdxzyeiQdRvMEVvlR8REiCqAsHrbMkymNF5Sl0Jxn8=,tag:5VU8oMvz/6SAo1zhmnToRg==,type:str]
        is_internal: ENC[AES256_GCM,data:LetV7mI=,iv:wAt1AeaOsiYlSG6Kn6Yk1QLDY5WTQkH7rhYlwUiqj7k=,tag:xGzpEjBSjGY7F4MnYlT4Qw==,type:bool]
        enable_icc: ENC[AES256_GCM,data:ZIsCuw==,iv:uhodT+twdpRG+BH0FYoC6iEtpUVN6mL8/KAZCVXIN4M=,tag:N8xENHUGlbArhwpw+kRR9w==,type:bool]
        network_mtu: ENC[AES256_GCM,data:4wPeNg==,iv:qW8uVvoZClQteRDfN7oHl7GHIi4xCUwIrMH+eel5Qao=,tag:DnDbvM2E+l2MmYlL2L+jrg==,type:int]
        interfaces:
            v4:
                subnet: ENC[AES256_GCM,data:gMr9zbE3QvzVD4w=,iv:mmTCia8s4lChz74mbosUSs3bhR8Dzv78gfUbooBIA1Q=,tag:vzTZxcYSBfEigILNVBZKHA==,type:str]
                gateway: ENC[AES256_GCM,data:HeuvOhkZa68=,iv:Ydp6ynvoDMMx0A416j39ax4kV3gBrlYfBPEyZBf5B20=,tag:d4+6/zr0ttAi1cfNmCJJHg==,type:str]
            v6:
                subnet: ENC[AES256_GCM,data:QQFbHC5w7uVQ66/NzMEo7WCH9w==,iv:bWmi8SwKrWj7xs4qTGZ8WKdOj4cPUvJvCKYd0bMDuw0=,tag:/GOWnDZvGQg8B4lNEEaw4w==,type:str]
                gateway: ENC[AES256_GCM,data:ChWxAxS+tSsIGluvkCiwAs8K07g=,iv:iuY6VLHJqFEKQjf3xKgQpcbo6jAeoDMFfiD+6G4NsB8=,tag:hOyvTmJqfSrluLG2q4V22w==,type:str]
    domainname: ""
    registries: {}
    tmpfs_size: ENC[AES256_GCM,data:IPjs,iv:ad/kPPOGw4nfVyOpnya/QhyNPn3kP+PFLziuFMqubzQ=,tag:8tLG5Op2/Shykio+x3rYnQ==,type:int]
    container_pid_limit: ENC[AES256_GCM,data:Atmd,iv:SIW9HFo68RdgUgJZNP/BtDV+iNSeUQKBqLqbWg0w0eI=,tag:gDbWtrPWodtZkRjFdrSMtQ==,type:int]
    installer_limits:
        memory: ENC[AES256_GCM,data:Ujx1vQ==,iv:nZrVXVdmPdk6p99CJZUNQ8Wd22epspLVbezGYWWRkAs=,tag:04Cu0UTzQlzykxKC7isXPQ==,type:int]
        cpu: ENC[AES256_GCM,data:dYPs,iv:91itEoU1lT+HtDE6xtnn2+Uy7UwbkdNV/bbIdBuLcPg=,tag:4EtbC7lhC/qqqZsdivIloQ==,type:int]
    overhead:
        override: ENC[AES256_GCM,data:nZoJZPs=,iv:U0DGTVExZ+QgP7bVLE8WPVtvTIXM47URz5s+Sj/XzHQ=,tag:YDQO/nxKP4CiwqGTteGhgQ==,type:bool]
        default_multiplier: ENC[AES256_GCM,data:WW3rHA==,iv:CmYljc6rdhCupFwySvhouICdDTYSI+jxsW5AZF8A+CM=,tag:ixzEz+oYBG2WIJPxGeXFaA==,type:float]
        multipliers: {}
    use_performant_inspect: ENC[AES256_GCM,data:RwDxrQ==,iv:VnPodFmHANo9sn90gn3J8YYTQVhkIfDLg/cDmfd3KIY=,tag:3O6jJ9AULXOt1Aelq6GSxA==,type:bool]
    userns_mode: ""
    log_config:
        type: ENC[AES256_GCM,data:7NPS9z0=,iv:Xj06JImQtFpG3/AFQWiLQeuDbkXxGiQQ8cJru9Gayvk=,tag:i+UXAeZM7iZrg1uLaoDmUA==,type:str]
        config:
            compress: ENC[AES256_GCM,data:Y4w4GD0=,iv:HrgyT2oyqMeoOlGZGVjFJeaYP8WsYml9nfxBGgo6YxY=,tag:ItbexbXNEIy6fAVzv0dBvA==,type:str]
            max-file: ENC[AES256_GCM,data:nA==,iv:K49gzw+3a9puDpqrd5c1N+xD+DlwWwrnB0poG3Yfl7M=,tag:G27Sp8ffqzcGMSmbhcwfwA==,type:str]
            max-size: ENC[AES256_GCM,data:vNw=,iv:uJ4KVLOKfZLsaontLRX8u5BPv/EBeShB9cI5NS3N+5c=,tag:9bv+KfEDIg19/9cpP2B0XQ==,type:str]
            mode: ENC[AES256_GCM,data:uTtcFMW22MRmv18C,iv:6JepxgF6UXeDspYAkqCWBZxgmhsOtJ3EEQTwROopASg=,tag:wgpkdgt+iPJ4xOsdSekklg==,type:str]
throttles:
    enabled: ENC[AES256_GCM,data:xeUz0Q==,iv:GgIRZkIzmuq7hQocucVIPO8qoI92vh/R1iH9W7qzr68=,tag:f3p6hqcKQa9+5FYHgTAsMw==,type:bool]
    lines: ENC[AES256_GCM,data:c0e/GQ==,iv:fUoRBu+agNcjkP2KA2ufwOuyFodK1cRXYdGdJk5S1hU=,tag:9wNQiMIQae5zSXPGJxJlCA==,type:int]
    line_reset_interval: ENC[AES256_GCM,data:IKsi,iv:n34yc3t8amKOETqRfpP18LCBUIQSztBaT4JuBvcie8s=,tag:DM2ceWIJJwcJxPWorUjWxg==,type:int]
remote: ENC[AES256_GCM,data:gJFIpa64JHrTDzMdBc0HWaysI2fcWqsmYvaj,iv:ZcdLCIY7S57k5e7OHTuilL+ZjodalzdsCejt/WFJzcM=,tag:LzjtaOyEf2TxuEdreV4g6w==,type:str]
remote_query:
    timeout: ENC[AES256_GCM,data:KhM=,iv:VAlcHmGTCJrge0rzeENseZ5FNdIZfkTvq3paB6yRbvc=,tag:UH/TLtId111giCCPBcoAKg==,type:int]
    boot_servers_per_page: ENC[AES256_GCM,data:koQ=,iv:6P9gOzMMbI0LE8oYpeMCA1lamJV7q0itoPGM04zmOOU=,tag:hdJMsObA0i8fABDTr/WZpg==,type:int]
allowed_mounts:
    - ENC[AES256_GCM,data:A03dKkGZuaw9LVQT6rMLvtESIuPDExW6ow==,iv:3KDnhTgayB8zNTfD1rRVSSJKBPMb/gu/jfbIBpOMr8c=,tag:NBpG3R51xec7qLx1Kowz4Q==,type:str]
allowed_origins:
    - ENC[AES256_GCM,data:9HdP0W3svJBRT6lGfHqiwx+Z3IHuwCT5AOTK,iv:GQp7+ts/BSYnEu7mTkzTV25fwaqczqO8n8L6gc6XnTE=,tag:LTYE8oD9poEY5C3/Q3vliw==,type:str]
allow_cors_private_network: ENC[AES256_GCM,data:V1ZddiA=,iv:7IjH7zbZ53/EWKIjs2QTQwWiNksh7pSsnAUriDqOl0E=,tag:RbhzWpPuTfvuBlJvRGO90A==,type:bool]
ignore_panel_config_updates: ENC[AES256_GCM,data:EAz+zYs=,iv:j9Psl4XnqmiXSVtSTBrAMXcDeSaHG310BHa8VHsRoYI=,tag:N1/n3sgYpcAnEajzR6CCiw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1es040kl2jhf632l7tjq0p8pea50krpf02znrl7m89zsftx829uqspnpl4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMFRiQTR2T2FDSHVmN0U3
            MEFuR293Z0Z1ZGlmUHBtV3JMUFJsZTFXTWxJCll3UE9FVThqM0FSLzlQOEFWNzhC
            cmYzQ3Z0WGxGd3lIejlyU0FsQkRDUmcKLS0tIHNyNE9wYkZNcmR3Y0FUUmVOSGR5
            elYvd3BqSSswYXlBMTNRUzl5TVlpNXMKaIPjozzVvn4baKz5vPZ/yNukQtyw5d2j
            nyAyVqu/D4+IZHOBZomvNX4eCblaRvC/ZRvSdMmZGz+ZOeIPIFLTGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-29T07:03:17Z"
    mac: ENC[AES256_GCM,data:EbWsu3l6mfRJ3PLwEtRhNq01/hGHEFuzipLOyst5wrR1IzFbwGE5tATbyYrK0g5KzfZzmsK/6HfnQTDorDiAS7QEYaeYwvQ935hZQwjCvPVwrqJdMpHPCFkzTnvOnBwmpiVH3R8GZs2NNRVXUVaqtLz8oi0bAWq260qLYH3m5so=,iv:RV/n81Y+aqL6d3M2bJ0feg8zkffaQ9n06QsJGo1iTgw=,tag:lEgfajC/k6XYArO3q7WBuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
