debug: ENC[AES256_GCM,data:eI2eM7o=,iv:plV5PaRnOeiPG/x4XjbxpED1EV9VwiG2+IPbrdOT01E=,tag:EkZJkeagLOBZhFrwHsuXqg==,type:bool]
app_name: ENC[AES256_GCM,data:M6K/4leww+u6HUU=,iv:gO3oxBTj6ABgH3smrqNz6pc2B46kqFnHCRaiMVf/6tk=,tag:qf+rI7upEce63+T7qHojuQ==,type:str]
uuid: ENC[AES256_GCM,data:ITq+T71Q5xSZEzkuyuimm7OijEHsxXxQKYTk5ITT+PU9FJ8w,iv:MiPwc8KMfm0HPs6LjB1PW6RLKFnxsmK4Booxwhta+ZQ=,tag:AuU16I4qs2zi37sxFSQEEQ==,type:str]
token_id: ENC[AES256_GCM,data:hS20OPPxSkJJ+Jb/zJ/h2A==,iv:5qMCi7te4jC0vaoA9sdykF6/IVWWV61UZLkCFZIFGHA=,tag:jyOU0/hu2ANcCuUp7X40GA==,type:str]
token: ENC[AES256_GCM,data:K+4lrslVVCccB9VmC0+6XFJbzzw+M9yPI2Gp1aiE5D3vIJcJKUzAZUfIjjApNHEG04wVmAxQGchMscqqJ0uKbg==,iv:k7f2H5SiS2hzevMSnDNv7pPzaa/odTFs+QU2PjN6z/E=,tag:3k+5jOVhpJFZUw8UZOU+fA==,type:str]
api:
    host: ENC[AES256_GCM,data:2MAkpmKLkA==,iv:MurJKBeYRxDKqaiuRb3Oq/TFapdZkPRKDOeDIAFl+0A=,tag:oEprEGAvVmBpBPfOmtb59g==,type:str]
    port: ENC[AES256_GCM,data:Vulz,iv:3AY02UFSnvf9icr0yFIv0ectRytWomUKcUbaLMPZb+U=,tag:MYTadXoQeLFTKyvjbHtZ8g==,type:int]
    ssl:
        enabled: ENC[AES256_GCM,data:PP3Umqc=,iv:GHdhsSDe3G/xcJdgH0oU9j5BkVsV1A1OnbJxm06EmJk=,tag:2EH1Oz8/VXAQRX3VxmB0Ng==,type:bool]
        cert: ENC[AES256_GCM,data:xPwpFaIYkzZrc6JM2oGrHN5CqKbJYIQs1XU3eEKNmbuBiyfG6S4+43osSeDIOh2fiRY=,iv:wdqxvgt5nGBi5TUHIgygppxaVGetaoRas3c7p7g/aVw=,tag:XaRRIato7N6+RcYDxtNrGA==,type:str]
        key: ENC[AES256_GCM,data:6NwhcSbz/r1N5wEkj7kLt2azUlmSBc7x3k9KVzts0QMq0fsjKrYEjNIniKZYZCHe,iv:17xXZm9L9E2IBqkggHLMg33Mem9xLNfsCqmT865nfcQ=,tag:IFVOUxTvawj3kNU/84tgTw==,type:str]
    disable_remote_download: ENC[AES256_GCM,data:MpuJUmM=,iv:/1AxK2aGbBlWbSJLZ3LOb9Yl7Ik6HBFuE1urAyKDqAo=,tag:pM7kKs5u+4UCWUNy9f9aaw==,type:bool]
    upload_limit: ENC[AES256_GCM,data:PEjN,iv:Nr+550vJ2kHoSksfwHCsJ5elqwci7eHrPlah6JLNnno=,tag:LwkUNLL+/l5M5YarFNnGAQ==,type:int]
    trusted_proxies: []
system:
    root_directory: ENC[AES256_GCM,data:ceNXTf2rDNSCx175I2UsxCtev+7ZPA==,iv:NBBYAc9FIqGM/iF0or4IU5vS/beqsC6w8MGxg0uaVyE=,tag:fT9ND/W/PjpvbAanxtDyAQ==,type:str]
    log_directory: ENC[AES256_GCM,data:iJY7hWRHOVeA5hUjaNpkfguHfaM=,iv:MJy2G9V2mRRwPAr1xwV56NjKzj7Oi62IeGr5RU5Oyg0=,tag:Gsh4MXtDcdq9jmXmu1jf2w==,type:str]
    data: ENC[AES256_GCM,data:MgYdyPAc0zlcgsC7q3iPyWcmcsS2+EjMKAbqyNET,iv:RE/2ji34WipaBPHEAM/z8Q/0MLLB8oEsa3G6wnqvSG8=,tag:FoiXKeGy+tFs023Hvz8ELg==,type:str]
    archive_directory: ENC[AES256_GCM,data:nV2WsXl15cni+f/9uVIhbDz47HM1uReYtGwSP2OV1A==,iv:Rec2zJncCQyTbVGlJ6z6epcbKpVPozHf1LjylQVpnO8=,tag:AkOEUArmaRkwXxrt/1X3oA==,type:str]
    backup_directory: ENC[AES256_GCM,data:6ARG0xj5I7NJx4Kxj0/k5Boz6pY0vC5IkGqpXpD1,iv:Ekx5z08CDJ9NXMNQR5QvV37PGtRKG0EIYAhIGJA4AqM=,tag:zonHh9JMXKu7Srq9JfSm8g==,type:str]
    tmp_directory: ENC[AES256_GCM,data:6GA6DGvHKv6Ze+imkqgCvQ==,iv:2VJhIi+g0tk+/yu+EUKNle2ZIMKRAiJFEuHpYv2oXBk=,tag:MNrjO+Czd+OK9nRScmDr6Q==,type:str]
    username: ENC[AES256_GCM,data:qQtZkcGgqJ3HDPg=,iv:CUkVmeopFxzztRhHyyLOsFBujctONAQ3DdOlBRri83w=,tag:7wL3SU0my3rh3IE3mcEWYQ==,type:str]
    timezone: ENC[AES256_GCM,data:MglS5AXFDUBUwk/FxEQiTww=,iv:tbVPiTmiP5RDTiOD5R+LFcA3gBmXTkocndpkZ+dTiQw=,tag:XVX186hG4nGdg1Z3e+0Y6w==,type:str]
    user:
        rootless:
            enabled: ENC[AES256_GCM,data:HE0BGfU=,iv:PbeFFd/jDNOV1swiZE7kOaLwML/IRQQC4CH3anxSLwk=,tag:/GWFOBGwQX50HXnbKuojZg==,type:bool]
            container_uid: ENC[AES256_GCM,data:IQ==,iv:MiM7a3lwyjMx48pzQPwpjBw7ILsSJ0SWFzdsu5O8PDo=,tag:G+xxK8K4sCI47cSEb/Vi1w==,type:int]
            container_gid: ENC[AES256_GCM,data:/g==,iv:F0+kNBcHk0eOy0VrXCAt/rZn+BZjuBlVnaktCukketI=,tag:8rWRt5LsGU3vv6CTXQA1fg==,type:int]
        uid: ENC[AES256_GCM,data:IRGX,iv:FxdDR38H9KvtKAEdJ30X+oRcjUDZp1FhracRY27C0I4=,tag:pl6CsMMIcZHVWX6GxoScWA==,type:int]
        gid: ENC[AES256_GCM,data:3kLi,iv:nVNHUPfunnMkNY3ysJgl555ca3RLhyX+p+FbwBJ+qXQ=,tag:lMFwAGDGZ7f+h72aXlJMow==,type:int]
    passwd:
        enabled: ENC[AES256_GCM,data:8zUimy8=,iv:0AqIPl5/8T11HZ0CBpMZUwkESNbzex70b2L6Dwm8sMA=,tag:kAofvirUuPxfZcMnmc3NXQ==,type:bool]
        directory: ENC[AES256_GCM,data:yOa7a8Y3nT/jKYcWY0E=,iv:o+Sq+kdhaxnKncniTIBUZp3u0I0LJ7HXUxQq0+eq0h8=,tag:GjpgBJ9w+C0xav2AnxbeDg==,type:str]
    disk_check_interval: ENC[AES256_GCM,data:O/07,iv:/QxOhh6QPobsCOkpiQAQcIexd+XoL6Es3w0X8y/60cQ=,tag:DoN8xqY/pvOuEAkEHeH8Ng==,type:int]
    activity_send_interval: ENC[AES256_GCM,data:SZU=,iv:0XJICgXFh5Gg/TDAWnRMU232dgLTZETXY0qtf2O9PQE=,tag:0JkMmv+XLL/fiG7mNQvnUQ==,type:int]
    activity_send_count: ENC[AES256_GCM,data:x3/o,iv:mGLSOIkIC/DIrA1BSRAAsVz9rP1dO4VPw09oWeO+MB4=,tag:u9mhLmE9RyKn9DlAzRkAiA==,type:int]
    check_permissions_on_boot: ENC[AES256_GCM,data:9HjI+A==,iv:GxkUjOqbRcHmLHbH4nJHRyMaOzODZQC+XaDPXGnfEzU=,tag:uNLDjCK53TOUM7Ho+6fMgw==,type:bool]
    enable_log_rotate: ENC[AES256_GCM,data:PBq71g==,iv:kc4OF/+OvfiCH1XK1RJ2pYpWbBBc8Rzw2+FwVPK77s0=,tag:JwOU0obwZ5+zSHt2TlSt3Q==,type:bool]
    websocket_log_count: ENC[AES256_GCM,data:cGKF,iv:1hx9YhVWBXKAjH13bYXIYmtKPwzkkDd/9KIPQ70lgXc=,tag:KW62dUJfCyyOfyJUXvvZLg==,type:int]
    sftp:
        bind_address: ENC[AES256_GCM,data:Y7RWhl0nig==,iv:ksrazbhs1oBUCzFAvp/NOP2c+PHv6l/quiGIxVqHCpU=,tag:TBlOIb008MpRqYYo3Sxu/g==,type:str]
        bind_port: ENC[AES256_GCM,data:8leXDA==,iv:tLdAxiOW+tSmJoIdEiD3l8eRJ+gQFemmBZirbD6hGCU=,tag:LZ8SOYoiHJF8gvFKPnGlKA==,type:int]
        read_only: ENC[AES256_GCM,data:z0Lkf5s=,iv:yTx9yqY+GdyzjJ2tH17C5toWRZG3s6fvioMeO8jgBbw=,tag:xuGku4HRBEXNIyLxJC6u7w==,type:bool]
    crash_detection:
        enabled: ENC[AES256_GCM,data:ACC++Q==,iv:WRXojO0rEEBX1qdUW85beFMeADMoNVH0Doidmls+XMI=,tag:3rl/Lz8BCJPSfkLZDnMC+A==,type:bool]
        detect_clean_exit_as_crash: ENC[AES256_GCM,data:oKsq7w==,iv:+X8l+9qfBkrfMitmo6Pvl3VPIvKbxRkQqTWPpSvNQXw=,tag:NnDyBTl/kD0jYSrh+CLWVg==,type:bool]
        timeout: ENC[AES256_GCM,data:b0o=,iv:LsxiI9B55nWNYsIWsR+5TBI4jAsUag4iTA42sg7w0hk=,tag:/+Bdo1Lg11+4+dNycruGeQ==,type:int]
    backups:
        write_limit: ENC[AES256_GCM,data:NQ==,iv:Bos4g+7uQPRfTWuNDwGl2NMUzHykoZ4RK/Ttw8sS4O0=,tag:1Rz8C4q/Wgd8ZpUu5m0xWg==,type:int]
        compression_level: ENC[AES256_GCM,data:qHAbwW0Ikp+j4g==,iv:xPrUwexF7600YhkOWtp/4+TiWwwS2+rK7ZIYvVckzdo=,tag:B3USLf39HnxfPJ5VaOwNWA==,type:str]
    transfers:
        download_limit: ENC[AES256_GCM,data:Xw==,iv:6HAy0jhEWO+iLG3hvnEQrxTwvuh4o5TRqJpKM89UjTU=,tag:ePWL1OyxtwRBDjUQzaUIWg==,type:int]
    openat_mode: ENC[AES256_GCM,data:/R48dw==,iv:BiwfICWgRZF7qWgLPGr2zKsVb3p17VKZ684O2gCeL8I=,tag:xxICETcAOriKYXhyuiCLCg==,type:str]
docker:
    network:
        interface: ENC[AES256_GCM,data:UJBuiKJuErM=,iv:Hte0mUAvL+M43R27JU41WiSByP82BxgCLloPy+53D3U=,tag:P6ic7vLkJvCvcUV7ca/Tgg==,type:str]
        dns:
            - ENC[AES256_GCM,data:xGbwbJ+GLA==,iv:gJu7aN664jsQqIZVE8XTXLfk2UBSqUQMN0r2d5cTswU=,tag:+hZmNkv8SG0MPR52F8xCjg==,type:str]
            - ENC[AES256_GCM,data:WLMKX7+UIQ==,iv:IbYXsB0zf0MDnPPnzQQ3++jIuR63LeHnVYuU36/D+VE=,tag:fbBy+eGT9nKQZzMncwFSAQ==,type:str]
        name: ENC[AES256_GCM,data:1VXUcRxiH4cD5uc=,iv:lno0LFs0cCD2de1rlnW5urOBATwnJFT5NQiVdO/pqhM=,tag:VInbRDEISoJL8EsW4HOiVQ==,type:str]
        ispn: ENC[AES256_GCM,data:zqyXurg=,iv:M6UTlfG73MMo2FerVm37C4p7bV+9+u+zE2Wq3jRhEEA=,tag:iTZlnn1NJye6t4MF5VkUBQ==,type:bool]
        driver: ENC[AES256_GCM,data:8pheKT3B,iv:utej8VxEW+MqmMsKNu+kB4ev4iOnaqNF66SnZGZD8e4=,tag:NfLU9DWUydG5jj8SdjknGg==,type:str]
        network_mode: ENC[AES256_GCM,data:+yGekqGno40bDm8=,iv:P62PP9Jxs9lmytEZTMqQE0JYXhfj1yDaq0A7skCRkHQ=,tag:Qs844Ks/Cc7Htj2+un8t/w==,type:str]
        is_internal: ENC[AES256_GCM,data:AJ6VSTo=,iv:fwkDp57rYpikR/uVZcYFi/YOJUCDSxNflDXg4p0TU80=,tag:t0l0q18ZSxFr75K5MZv9Mw==,type:bool]
        enable_icc: ENC[AES256_GCM,data:+EvskA==,iv:ABpanJXYGvGdZKaoR6J1jRFaLvvaz3FUHW/v4/xF7f4=,tag:tOia3+G8Ftejcfi4WRavNg==,type:bool]
        network_mtu: ENC[AES256_GCM,data:Ccy22w==,iv:oxUPT2IKSqXLnJrkGm6Jy3/BHcwKsFtk617aTAvXlfM=,tag:smF9dnEcJtigHPYz4P6mmg==,type:int]
        interfaces:
            v4:
                subnet: ENC[AES256_GCM,data:9NG/aZaVV00f01Q=,iv:w5DV1IVUdwNXj/pFu7OJEjDuTWeFaBIJDdn4zu312L4=,tag:Wa55dnFMoVUKvx4HufBoVQ==,type:str]
                gateway: ENC[AES256_GCM,data:QFX1DVc7oAg=,iv:KzCV4ug3MSUjsSBnqgFlqVK0rmNEz1bDF0sfZmWnbb0=,tag:bx4eniqK349ep5cazqKF2g==,type:str]
            v6:
                subnet: ENC[AES256_GCM,data:nDyB8wiBOQvkCVmmbIgk2BTAwA==,iv:rwUYLKX9SCozWVRJPaj2XTiatrdqnTHKHeDTg6qPPa0=,tag:veEZqGJqqby3wX4cjCG6UA==,type:str]
                gateway: ENC[AES256_GCM,data:VOMybzjjQDPZe7ooL4XZo6TxsBM=,iv:WTXWRfdZzXQm7KPCQj2Yyqr27YVcbWWXbIM+FECLp1w=,tag:qtAVpmh25yiORgNzLSE6FA==,type:str]
    domainname: ""
    registries: {}
    tmpfs_size: ENC[AES256_GCM,data:cDAO,iv:K/IOMIx9ztvsKvvMm5CGrArH20Eom9KNdkGmsFu9NW4=,tag:yzGPnRZ7X08U8akxydaDEg==,type:int]
    container_pid_limit: ENC[AES256_GCM,data:N8Ae,iv:Fm9WERunzKg+7kDfkZKWQ9X3eICExz13OUw5C/qA5nk=,tag:2bPaUuF4LCZzMReOLxi3aQ==,type:int]
    installer_limits:
        memory: ENC[AES256_GCM,data:qwDEzg==,iv:pM2kgNAojMSxsz3g+L6ccD1PLkJ7SLEkaukMjNSP96U=,tag:zMF1ujxW7snbKyifHBXK/g==,type:int]
        cpu: ENC[AES256_GCM,data:DQe0,iv:3g4w1yMYpEzhh83XgRdz9RwL/KZJVyAaYPxRnccBuzQ=,tag:iAIS80TPpSpTJ5x2+tRbnQ==,type:int]
    overhead:
        override: ENC[AES256_GCM,data:xny1OHY=,iv:jVUfxvKMrpxRDX62+cmhMjJtyzr8JRN8RD/hPV0Xeto=,tag:K/0vhsmcgPhz4EUkICrCKA==,type:bool]
        default_multiplier: ENC[AES256_GCM,data:yoX7KA==,iv:AepV3ZZnhPhm4dbUXS+bRok1NvWVveyN4gRvVhycC6Y=,tag:aqPKh7hP5V4JVfqHegvL1Q==,type:float]
        multipliers: {}
    use_performant_inspect: ENC[AES256_GCM,data:xEEXCA==,iv:amsIUKIAOAqEKb6QdVPPLNhGxB0Cq+X5jMSRvjwdsvU=,tag:C1422CkZc8YrmD2B1mBc4g==,type:bool]
    userns_mode: ""
    log_config:
        type: ENC[AES256_GCM,data:P4cEaE4=,iv:7BOOA/MFsilqCQG940DNY2wmvXuazILbRkA8y2Pc35k=,tag:aREslKJoFLchQXGD/qGg7w==,type:str]
        config:
            compress: ENC[AES256_GCM,data:n1R7PnY=,iv:GKR6NpgLXKprtAap5DRSVA7CXtgR5qVlg/f2klFMD28=,tag:Th8yqfVu435rWGHg6y3jrQ==,type:str]
            max-file: ENC[AES256_GCM,data:RA==,iv:A/ZGWEPlJVinGH8WEr1TAzTUwZUkiy1sb/jHcczNSeo=,tag:UHiTtAPvmeeyg4Yu23KYHQ==,type:str]
            max-size: ENC[AES256_GCM,data:wMI=,iv:9HYWZLm48iUSGWf+kZEj1HIjstHEyxH+R4u6Awvh1qM=,tag:Vj1t+d35dekIIuX/xnmF1A==,type:str]
            mode: ENC[AES256_GCM,data:j5QF9w6WtWSDnkZD,iv:lILsBBa1R0daDyLj+1QiYlixnaWyn+Wq3g2j5AxeSrA=,tag:+VI+Dnt/mBdnJet5XK4Vnw==,type:str]
throttles:
    enabled: ENC[AES256_GCM,data:51mvvA==,iv:6mD4TKo5odClGh9t8NjBom80FNE+/iQ560XoxwL8TD4=,tag:5wCtcgXcNQ9n5wp+AU5Wjw==,type:bool]
    lines: ENC[AES256_GCM,data:ido/FA==,iv:vW9eQ9BxJavpLVNc0E0N8lc60mH74IKbmPEaKAqod6o=,tag:ZUpFxj2ae9l7Ak227AqRoA==,type:int]
    line_reset_interval: ENC[AES256_GCM,data:ULff,iv:AUivKdA+0qPyOrcbAjHeIeuROAlzM7eerkED03CqsN4=,tag:rxILBdVR6xnp/a2HAszV/g==,type:int]
remote: ENC[AES256_GCM,data:VS4Wcv43vILFP0ZBjOuwbFiLaud9mQomyjCe,iv:vniC47ZZNNJ7lD8CtJWzY7pcT2oa6JAcDuSep6MCnLc=,tag:Tdwn/35v719nSP1vbkCNMw==,type:str]
remote_query:
    timeout: ENC[AES256_GCM,data:+YQ=,iv:CM5yLM09HfGWo83BKvz499yILRBzfmM3J42PpYqfL8c=,tag:1WvIa567uZ687vlZtn1RcA==,type:int]
    boot_servers_per_page: ENC[AES256_GCM,data:jHw=,iv:awuQAng7Duaj+wo7iL5xurtXzYvcrOo5IFbVO5eUB/w=,tag:KwbKH59OtHnwb9k7Zz0EWw==,type:int]
allowed_mounts:
    - ENC[AES256_GCM,data:6w7MlKMsVjyK03URsE6phq2srJWJlIJAow==,iv:Q6DUi/tpWEiO88M9AqJgGUWht28qIj6PcJJcf3bXsqU=,tag:/Ylb5AMFcpFsLaMYGr2ebA==,type:str]
allowed_origins:
    - ENC[AES256_GCM,data:ZQ1EmD7wQ0CnjuG8HQF3SJIyXZS9G4n+eMQK,iv:yy48OXVgskyx4gieEBkXCotajNGI1/MOhnTxobiuZDc=,tag:qCYzJfSrXGJRJFGSEleNTQ==,type:str]
allow_cors_private_network: ENC[AES256_GCM,data:Mo+FH1Q=,iv:1FzIdVzgnjRedHGmupFwFehAy0NVzUMKnkwUiKfFICo=,tag:7bLH3UCG2qyV0U95CVPoOg==,type:bool]
ignore_panel_config_updates: ENC[AES256_GCM,data:PYp795Y=,iv:VC0WK3tIQpubm7NNVOtaiqFzRB9x0mO3462Rp0WKoM0=,tag:VUk8aNT3QYhMXmyRKGkGpQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1es040kl2jhf632l7tjq0p8pea50krpf02znrl7m89zsftx829uqspnpl4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoREcvNFVKbDRsZDkvMjBZ
            MGlRZXNoNHg1SlFCUkpOU3ZnaGl3M2Nhekc0CmFxWVhtblVya0lLVFczS2JIUDJj
            dEF2S3Y1M2ZRVFdnaDlXaEJEMWJRRDQKLS0tIDlVcGZmckhtUHV3NGJJSGRmL0Vk
            RjRxU1ErSnplcUpsVnozVzFaOVJuRDAKeR/UJsDDNcvs++fA6MBXTaqpAu4s26Cy
            kN79FZWqAxkNGOOYwCcEFaTjORs5/8yXdPV18rTDbGmyXPT3rYfNwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-29T06:36:58Z"
    mac: ENC[AES256_GCM,data:9ZWpM8OWudEBmyWjLM+P0vqcDcH2b54oy7seDcbOPtpvZEvaLPtrwrva8cRN0xnDy/HKG0UGZIEfULc3nREJCIUZg6AtOC2cn20xzzzRDnI6/sQQhZrDKjb6y29TjPbxJPqu6QSPSWDMjDa6TO95K9T4Zp396362zc1/jDsPdNs=,iv:E/1f4Dw8g/CdeXR6E6QXS0Z1TiZa1KvwSaNdyTSWNbo=,tag:StC3giHb74qcBFUluqbG9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
