version: '3.8'

services:

    database:
        container_name: panel-database
        image: mariadb:10.5
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        env_file: .env
        networks:
            - panel 
        volumes:
            - ./data/database:/var/lib/mysql

    cache:
        container_name: panel-cache
        image: redis:alpine
        restart: always
        networks:
            - panel
        env_file: .env
        depends_on:
            - database

    panel:
        container_name: panel
        image: ghcr.io/pterodactyl/panel:latest
        restart: always
        env_file: .env

        depends_on:
            - database
            - cache

        networks:
            - panel
            - minio
            - traefik

        links:
            - database
            - cache

        volumes:
            - ./data/var/:/app/var/
            - ./data/logs/:/app/storage/logs

        healthcheck:    
            test: [ "CMD", "curl", "-f", "localhost:80" ]
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 5

        labels:
            traefik.enable: true
            traefik.http.routers.panel.rule: Host(`panel-home.domain.com`)
            traefik.http.routers.panel.entrypoints: https
            traefik.http.services.panel.loadbalancer.server.port: 80

networks:
    panel:
        name: panel
        ipam:
            config:
                - subnet: 10.2.1.0/24
        driver_opts:
            com.docker.network.bridge.name: panel
    minio:
        external: true
    traefik:
        external: true
