services:

    database:
        container_name: panel-database
        image: mariadb:10.5
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        env_file: .env
        networks:
            - panel 
        volumes:
            - ./data/database:/var/lib/mysql

    cache:
        container_name: panel-cache
        image: redis:alpine
        restart: always
        networks:
            - panel
        env_file: .env
        depends_on:
            - database

    panel:
        container_name: panel
        image: ghcr.io/blueprintframework/blueprint:v1.11.6
        restart: always
        env_file: .env

        depends_on:
            - database
            - cache

        networks:
            - panel
            - minio
            - traefik

        links:
            - database
            - cache

        volumes:
            - ./data/var/:/app/var/
            - ./data/logs/:/app/storage/logs
            - ./data/extensions/:/blueprint_extensions

        healthcheck:    
            test: [ "CMD", "curl", "-f", "localhost:80" ]
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 5

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.panel.rule: Host(`panel-home.domain.com`)
            traefik.http.routers.panel.entrypoints: https
            traefik.http.services.panel.loadbalancer.server.port: 80

    wings:
        container_name: wings
        image: ghcr.io/pterodactyl/wings:latest
        restart: unless-stopped
        command: wings

        networks:
            - wings
            - traefik

        expose:
            - 443

        depends_on:
            panel:
                condition: service_healthy

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/lib/docker/containers/:/var/lib/docker/containers/

            - /mnt/tank/docker/wings:/mnt/tank/docker/wings

            - ./config.yml:/etc/pterodactyl/config.yml
            - ./logs/wings/:/var/log/pterodactyl/

            - /tmp/pterodactyl/:/tmp/pterodactyl/
            - /etc/ssl/certs:/etc/ssl/certs:ro

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.wings.rule: Host(`wings.domain.com`)
            traefik.http.routers.wings.entrypoints: https
            traefik.http.services.wings.loadbalancer.server.port: 443

networks:
    panel:
        name: panel
    wings:
        name: wings
    minio:
        external: true
    traefik:
        external: true
