services:
    diun:
        image: crazymax/diun:latest
        container_name: diun
        command: serve
        restart: always

        volumes:
            - ./data:/data
            - /var/run/docker.sock:/var/run/docker.sock

        env_file:
            - .env

        networks:
            - diun

        labels:
            diun.enable: true


networks:
    diun:
        name: diun
