version: '3'
services:
    paperless-redis:
        image: docker.io/library/redis:7
        container_name: paperless-redis
        restart: unless-stopped

        volumes:
            - ./data/redis:/data

        networks:
            - paperless

    paperless-gotenberg:
        image: docker.io/gotenberg/gotenberg:7.10
        container_name: paperless-gotenberg
        restart: unless-stopped

        command:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"

        networks:
            - paperless

    paperless-tika:
        image: ghcr.io/paperless-ngx/tika:latest
        container_name: paperless-tika
        restart: unless-stopped

        networks:
            - paperless

    paperless:
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        container_name: paperless
        restart: unless-stopped

        depends_on:
            - paperless-redis
            - paperless-gotenberg
            - paperless-tika

        ports:
            - 8000:8000

        volumes:
            - ./data/data:/usr/src/paperless/data
            - ./data/media:/usr/src/paperless/media
            - ./data/export:/usr/src/paperless/export
            - ./data/consume:/usr/src/paperless/consume

        env_file: .env

        networks:
            - traefik
            - paperless

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.paperless.rule: Host(`paperless.domain.com`)
            traefik.http.routers.paperless.entrypoints: https
            traefik.http.services.paperless.loadbalancer.server.port: 8000

networks:
    paperless:
        name: paperless
    traefik:
        external: true
