services:
    share:
        image: caddy:latest
        restart: unless-stopped
        container_name: share-server

        volumes:
            - ./data:/files
            - ./Caddyfile:/etc/caddy/Caddyfile

        networks:
            - traefik

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.share.rule: Host(`share.domain.com`)
            traefik.http.routers.share.entrypoints: https
            traefik.http.services.share.loadbalancer.server.port: 80

networks:
    traefik:
        external: true
