version: '3.9'
services:
    adguardhome:
        container_name: adguard
        image: adguard/adguardhome
        restart: unless-stopped

        ports:
            - 192.168.1.200:53:53/tcp
            - 192.168.1.200:53:53/udp

        volumes:
            - ./data/config:/opt/adguardhome/conf
            - ./data/work:/opt/adguardhome/work

        networks:
            - traefik

        labels:
            traefik.enable: true
            traefik.http.routers.adguard.rule: Host(`adguard.domain.com`)
            traefik.http.routers.adguard.entrypoints: https
            traefik.http.services.adguard.loadbalancer.server.port: 80

networks:
    traefik:
        external: true
