
services:
    cupdate:
        image: ghcr.io/alexgustafsson/cupdate:pr-80 
        container_name: cupdate
        restart: unless-stopped

        env_file:
            - .env

        volumes:
            -   /var/run/docker.sock:/var/run/docker.sock:ro
            -   target: /tmp
                type: tmpfs

        networks:
            - traefik
            - cupdate

        labels:
            traefik.enable: true
            traefik.http.routers.cupdate.rule: Host(`cupdate.domain.com`)
            traefik.http.routers.cupdate.entrypoints: https
            traefik.http.routers.cupdate.middlewares: authelia@docker
            traefik.http.services.cupdate.loadbalancer.server.port: 8080

networks:
    cupdate:
        name: cupdate
    traefik:
        external: true
