version: '3'

services:
    infrared:
        image: 'haveachin/infrared:latest'
        container_name: infrared
        restart: unless-stopped

        ports:
            - 0.0.0.0:10101:10101/tcp
            - 0.0.0.0:20000:20000/tcp
        
        env_file:
            - .env
        
        expose:
            - 10102

        networks:
            - traefik
            - metrics

        volumes:
            - ./configs/:/configs


networks:
    traefik:
        external: true

    metrics:
        external: true