
services:
    kustos-db:
        image: postgres:16
        container_name: kustos-db
        restart: unless-stopped

        env_file:
            - .env

        ports:
          - 5432:5432

        networks:
            - kustos
            - bytebase

        volumes:
            - ./data/postgres:/var/lib/postgresql/data

        healthcheck:
            test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    traefik:
        external: true
    bytebase:
        external: true
    kustos:
        name: kustos