services:
    share:
        image: caddy:latest
        restart: unless-stopped
        container_name: caddy-file-stash

        volumes:
            - ./data/build:/app
            - ./Caddyfile:/etc/caddy/Caddyfile

        networks:
            - traefik

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.files.rule: Host(`sailboat.domain.com`)
            traefik.http.routers.files.entrypoints: https
            traefik.http.services.files.loadbalancer.server.port: 80

networks:
    traefik:
        external: true
