version: '3.8'

services:
    wings:
        container_name: wings
        image: ghcr.io/pterodactyl/wings:latest
        restart: unless-stopped
        command: wings

        networks:
            - wings
            - traefik

        expose:
            - 443

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/lib/docker/containers/:/var/lib/docker/containers/

            - /mnt/tank/docker/wings:/mnt/tank/docker/wings

            - ./config.yml:/etc/pterodactyl/config.yml
            - ./logs/wings/:/var/log/pterodactyl/

            - /tmp/pterodactyl/:/tmp/pterodactyl/
            - /etc/ssl/certs:/etc/ssl/certs:ro

        labels:
            traefik.enable: true
            traefik.http.routers.wings.rule: Host(`wings.domain.com`)
            traefik.http.routers.wings.entrypoints: https
            traefik.http.services.wings.loadbalancer.server.port: 443

networks:
    wings:
        name: wings
        ipam:
            config:
                - subnet: 10.2.2.0/24

    traefik:
        external: true
