
services:
    beszel:
        image: henrygd/beszel:latest
        container_name: beszel
        restart: unless-stopped

        volumes:
            - ./data:/beszel_data

        networks:
            - traefik
            - beszel

        extra_hosts:
            - host.docker.internal:host-gateway

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.beszel.rule: Host(`beszel.domain.com`)
            traefik.http.routers.beszel.entrypoints: https
            traefik.http.services.beszel.loadbalancer.server.port: 8090

    beszel-agent:
        image: henrygd/beszel-agent:latest
        container_name: beszel-agent
        restart: unless-stopped
        network_mode: host
    
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /home/zero/.beszel:/extra-filesystems/home:ro
            - /mnt/tank/.beszel:/extra-filesystems/tank:ro
    
        env_file:
            - .env

networks:
    beszel:
        name: beszel
    traefik:
        external: true
