

services:
    minio:
        image: minio/minio:latest
        container_name: minio
        restart: unless-stopped
        command: server /data-1 /data-2

        user: "1000:1000"
        
        env_file:
            - .env

        volumes:
            - /mnt/tank/docker/minio-volume-1/:/data-1/
            - ~/minio-volume-2/:/data-2/

        networks:
            - traefik
            - minio

        ports:
            - 0.0.0.0:9000:9000

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.s3.service: s3
            traefik.http.routers.s3.rule: Host(`s3.domain.com`)
            traefik.http.routers.s3.entrypoints: https
            traefik.http.services.s3.loadbalancer.server.port: 9000

    minio-console:
        image: ghcr.io/georgmangold/console:latest
        container_name: minio-console
        restart: unless-stopped

        user: "1000:1000"
        
        env_file:
            - .env

        networks:
            - traefik
            - minio

        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.minio-console.service: minio-console
            traefik.http.routers.minio-console.rule: Host(`minio.domain.com`)
            traefik.http.routers.minio-console.entrypoints: https
            traefik.http.services.minio-console.loadbalancer.server.port: 9090

networks:
    minio:
        name: minio
    traefik:
        external: true
