version: "3.8"

services:
    minio:
        image: minio/minio:latest
        container_name: minio
        restart: unless-stopped
        command: server /data-1 /data-2 --console-address ":10101"
        user: "1000:1000"
        
        env_file:
            - .env

        volumes:
            - /mnt/tank/docker/minio-volume-1/:/data-1/
            - ~/minio-volume-2/:/data-2/

        networks:
            - traefik
            - minio

        expose:
            - 9000
            - 10101

        ports:
            - 0.0.0.0:9000:9000


        labels:
            diun.enable: true
            traefik.enable: true
            traefik.http.routers.s3.service: s3
            traefik.http.routers.s3.rule: Host(`s3.domain.com`)
            traefik.http.routers.s3.entrypoints: https
            traefik.http.services.s3.loadbalancer.server.port: 9000

            traefik.http.routers.minio.service: minio
            traefik.http.routers.minio.rule: Host(`minio.domain.com`)
            traefik.http.routers.minio.entrypoints: https
            traefik.http.services.minio.loadbalancer.server.port: 10101

networks:
    minio:
        name: minio
    traefik:
        external: true
