config:
    bind: ENC[AES256_GCM,data:1jdA5U//u8vwvYEsvQ==,iv:roBV/XUJqzSqtHy2yruwjvrLMJIm367RzQj7zQA2S/A=,tag:ja27PdmMLJ2DsAxAtcDTYQ==,type:str]
    proxyProtocol: ENC[AES256_GCM,data:Q8LQkA==,iv:GfqsbL+0UBnvlAXEpZbKXUoO2830uO0i7KjOn40NGw8=,tag:+A1rpAlVRlrNqoTQsfaEKg==,type:bool]
    lite:
        enabled: ENC[AES256_GCM,data:8YBb0g==,iv:+2/aFoMRMYRvb/W1wvBrtvQ0fVM0KZR0gvoTMm6SIkA=,tag:q7/xBDakiECV5iFqUYy2vA==,type:bool]
        routes:
            - host: ENC[AES256_GCM,data:pF+ACpwb30lkm3e8,iv:4U4Ua7q+UAatLjIeL0N4D9MnTqbjgKGweLMvskuLM9s=,tag:MwWkj0pfqbYHCXQVOqjKgQ==,type:str]
              backend: ENC[AES256_GCM,data:Pc8grTS9IcWZ75zRPTM=,iv:Bs7EVfq2bqLouFLfq4VJ/vgHoxkXvGNyraRyRqFi3Zc=,tag:8DoXzssomvSFVmzcTdOAGQ==,type:str]
            - ENC[AES256_GCM,data:c0M31tXOH3aPsqaKxJA=,iv:LRESQ94QO4I90VcFKpnQa7+2QK6J2MLMq8eQh9tNYAk=,tag:4xhCuJlOlopL5meKtr4snw==,type:comment]
            - ENC[AES256_GCM,data:28wPxPd/EDE2wR5jdZhPpkg+2AMl2YloagvgRw==,iv:CdTFvhA6WhXigOQ3G4qaaY9y+qHlWeIn+73BdSwoYew=,tag:XN5McsR4uN+Uu/Alb02M4w==,type:comment]
            - host: ENC[AES256_GCM,data:fGEuXC9xDPS9dzUixBkKzA4h9pqTLFCa,iv:k49guxnfORQfc+RrgIICorJLg+n02sN7+ptHRzK2PYo=,tag:pAbk1IUuIgg8yjLLsZHzjQ==,type:str]
              backend: ENC[AES256_GCM,data:fD6SKNfkUss/teNaiOI=,iv:kQiKmQeg27nOriSXBuVkHPYyvIGgFQuRH1Eeav0DW+U=,tag:FspVaupgs/tu5SJbE9pM5g==,type:str]
            - host: ENC[AES256_GCM,data:sUQNmZ9dbjkKM/PirUogtg==,iv:Soz44IZ3g6HKllHBgiiY4czXSa9iVl1aC6L7ug4Z4u4=,tag:75MHkBfpcFXSD5rh7ZkkOw==,type:str]
              backend: ENC[AES256_GCM,data:4uSNkvqVKcNpr1q65M4=,iv:ZX13KVfDX/mzbgnDe2Kwi9HwRTbiIGs8cvnn4AUvRfo=,tag:sWeo0SRUkQdM9l7nczkXVw==,type:str]
            - host: ENC[AES256_GCM,data:2U3UgjU7pJb4ks0zJ0rhUlw=,iv:5Q+noKsDzgbPyNTCIpkQo7m4H61QLr0Jb3GuL7akRso=,tag:aV/VaTLCpVEMEuApKKbQ4Q==,type:str]
              backend: ENC[AES256_GCM,data:p+bBHuCKB2T5CrYI43Y=,iv:GVn0sCst3cAbywWHMLxSHPgprZ7YOsVOgD9Duoh6B1c=,tag:3t5VxJ1DF+cs5yKOiuWyuQ==,type:str]
            - host: ENC[AES256_GCM,data:FrwFqrHD1un7AeeO1A7Orw==,iv:EOB/KqTC5qLO+EGFWEJfOoZKaLZEejP3k3eh6k9qUNg=,tag:CpBWnh6ZiS5zI0/VRwjdzg==,type:str]
              backend: ENC[AES256_GCM,data:k5Q+MEnK7jK6O74d2cw=,iv:95J8Yh0T6Cf34GgF8fpGbAJg2PbsVhy3b6HlPPXHFS8=,tag:cyNWZWLNduz6O8LC0wIPDA==,type:str]
            - host: ENC[AES256_GCM,data:VlH1jq4nYYB/+MkhP6S53TUZSA==,iv:Tm0ZRiY4BQXNZkvZkDwrb0gaQ0JcLQmJZwr/CwjayFI=,tag:PKlnKVJ8x7zwyx3vOn23JQ==,type:str]
              backend: ENC[AES256_GCM,data:79tYd+PFg6yzXDk29Sc=,iv:I+3N15YmZNLDXxbS5bexXIsujirnxUBW0YxkTo/MSx0=,tag:gy1lrOeL/aiW6y+mguAWug==,type:str]
            - host: ENC[AES256_GCM,data:Fyj1Q6xW1d9Jk04VPPPr2oN8gJbZ,iv:DgvUvKt9RUbO5g6xfA7UEMFErejHnK7PfXHxHEisL8o=,tag:WuQOOVj42dO6IhQCjg6TPA==,type:str]
              backend: ENC[AES256_GCM,data:5Z8uKPDd3yRKueCXfPk=,iv:ZrzHnS3HLlSWYLq2y1sC7DLrfMPQN+MwtEvi2ejk63Y=,tag:8Wl1cRi1sKp/9TQBWwP5wA==,type:str]
            - host: ENC[AES256_GCM,data:cdF0SNIbQt0AxTu7jCWNIYmq8g==,iv:Y4+r5iu1I5HYlTkEDZwbUIHpgmXFm5oocGvMClSJYU0=,tag:wX435UnmEKK+ed6h6AzzPA==,type:str]
              backend: ENC[AES256_GCM,data:Y9b5QZTQsmP2VKZYWyI=,iv:4q0aRu4iQUjabQnlADq0y5skrcNSPbdFUMmTlehXz4A=,tag:EYOrGC6ebFk3f5tSYtlp4w==,type:str]
            - host: ENC[AES256_GCM,data:m0bIWVQjOABUyScfCJRvPHWHJ7z9,iv:Zwa5C9JnAUEaavQuC8ABYEF060EXHq1YY/cXgLOshNc=,tag:ivCkuh2Q8BXPpjwoFCP+IQ==,type:str]
              backend: ENC[AES256_GCM,data:/Xf0JqaMxEiVXt0pyvA=,iv:Kty+J7z2ATb+g7PVzPgciI4IW9IZjIVuYomV/k5oFAk=,tag:XrxmNDZ/eJ8dvGfMNTyQ2Q==,type:str]
            - host: ENC[AES256_GCM,data:YCzutApTbwDTJhEim513k5s=,iv:j3lCr4Q723750K4zOpQ74ntkmTvT/+4UeqbrmGY/Rc4=,tag:EquP9saKU8HLBhN8q9Y06A==,type:str]
              backend: ENC[AES256_GCM,data:WIKQFFo91ou2ClAfSg4=,iv:BBvAkHXi8X5mowfiObymp4E5padK1fVcsqAh1lUoekY=,tag:2zCSgOB/EwHhzWRSwO1+QQ==,type:str]
            - host: ENC[AES256_GCM,data:OLfr5LMDHomWuJsdEQ==,iv:LO9mraCxOjvNy0HHhvVRESOie50mRpe1C3x9G1gVt88=,tag:rsejJl6hybh4Q3CptdzMdA==,type:str]
              backend: ENC[AES256_GCM,data:/JQ1gCIqoGKvfuzkoGY=,iv:XVNpAbGqpuaH08FIacK+DjltZtVjZ3UdK1R9FeSlheU=,tag:+4+Ye1RuNa3LApXCkZ1Vtg==,type:str]
            - host: ENC[AES256_GCM,data:oDTNw8klyCelfyF9F1NxHw==,iv:wpdTua2Yn7rnEG3A0goBJjMyd0u8vJ2/d49m7WwDOP8=,tag:Tn2rKOckODBT3/mOA8IT9g==,type:str]
              backend: ENC[AES256_GCM,data:T7gx+/hSQ8IjK5+Jxkw=,iv:aGP3XCxDt4K1k+cTQ/K9qJjXDtmmhBpADO72z/UL8Go=,tag:oKExn32nAvfMqZ2ZCGFpVQ==,type:str]
            - host: ENC[AES256_GCM,data:IiXQv/9MEgzNw5qUqRg=,iv:uQdaC25fdyUPPXCFHw8iC866O1UfZKglP1yY2XX/fQA=,tag:facSUOBleVpBRuuwW+kztQ==,type:str]
              backend: ENC[AES256_GCM,data:81gIjefB5rHGqtwiTV4=,iv:87FUR6RDaCBtRk7nbYAEaGH+AC4BVU7FEeE+EagPs14=,tag:jy+Kv1E0Eh7gGev/qvqgKA==,type:str]
            - host: ENC[AES256_GCM,data:fTEtbBDCXiE3OIHsbes=,iv:g5gFe0SOCvx71/yjUdPMz3zCjnZlKoB4bhTSDo5u/Lo=,tag:Y/TwLVFv7nyPXkcNY4qM4w==,type:str]
              backend: ENC[AES256_GCM,data:+RAiQxX45eIofE97Lgs=,iv:LdQ/Grv9lDHxyJUksiPdImNkuZzk/BS9oZerpXmHX3Y=,tag:/TmZ+OiD+lf55UZFwz+lbA==,type:str]
            - host: ENC[AES256_GCM,data:tcXDUlXsfhWQX9RQctUHRwWZ,iv:UhwlVlUIonxt2PL8MTsIuIfeIlwMzYhd4qFWQs8q9eY=,tag:nfqHZB1docctYao9lF3rdg==,type:str]
              backend: ENC[AES256_GCM,data:2R9WX9Z0moJBI77GjOE=,iv:5QQ6lS9dnbpQRCA5lKOvhgnm8tQ6oO9xSBcXxfb8w9g=,tag:JJUR2MeAHqAp6IjSYfa6oA==,type:str]
            - host: ENC[AES256_GCM,data:2RaSAuZdM0K4rg7GQR9/DNo=,iv:x12Q/OwVovUcgLNXKaGAqCl+X+5MeGYmS880KBRZK7M=,tag:g80azsUMz9vnBSFcbabtlg==,type:str]
              backend: ENC[AES256_GCM,data:lO/LfBIB6eM+w6BD3JU=,iv:/NwAlkxj0IFysok3xSdUsxWetCvszFc7C4PGJ5Y5PDU=,tag:lNyE3WIDhlIrP6GvEyjPkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1es040kl2jhf632l7tjq0p8pea50krpf02znrl7m89zsftx829uqspnpl4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZmg2RUlYZVFsTmFYMnZp
            NFZocFNXcFZYZnRhdVptVWwxVjN0YXQzRkN3CkNJN0ZIUU9xQnJza2EvbXFDSm9B
            cUdUTnFWMEQycUNKSG5JRGttTUJvQWMKLS0tIFRUNnlOaU9uaTdPZmUvL251ODhH
            cGl1bXduV0FhTFVGTXNxYkJjZ3BMcEkKYS0cWzrNpcLF+5uKQgpgmFfFCeF2tYo9
            3/aUQV9qmTTFFaJjvmf7oIO2ruY/dcrpHQrxSh+Q71gROdB/OECG0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-29T06:36:58Z"
    mac: ENC[AES256_GCM,data:UquBF4bMqM86T7MJmfghlqmke1/gBcxaxWK7I8L6mtNaCVEcq2gFxz2nVGci06mBZI9iRton9BkbxsXJMrSv3nac7LDWYhOkNQSQmE1qvaw39sWg2Xh+o0L3RAIj+GR8gf+rsqHAbNB9v4ajV/3U0Fr6MjMgIzLJwLOv14SeN0c=,iv:RpBMGZKOu1KOnhQMfVgzEc/yFVpqmoE3S2Pbldd/ags=,tag:1HjH5gKmFSTGFpyzQUacGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
